### ISSUE TITLE
can't use in simulator

### ISSUE THREAD

**Issue by mvolkmann** [apotocki/lua-iosx#1]
When I try to use the `liblua.a` file produced by this when running a SwiftUI app in the Simulator I get "building for iOS Simulator, but linking in object file built for iOS". Do you know what I need to do to create a `liblua.a` file that I can use to run in the Simulator?

**Comment by apotocki** [comment]
You don't need to put libs from xcframework directly. Just add lua.xcframewtork into the project ( https://www.simpleswiftguide.com/how-to-add-xcframework-to-xcode-project/ ) and Xcode will find the appropriate lib automatically for the selected platform. But it's much more comfortable to use cocoapods to manage external dependencies like lua-iosx.

**Comment by mvolkmann** [comment]
Thanks so much! That worked for me! The issue can be closed. R. Mark VolkmannObject Computing, Inc.On May 1, 2023, at 4:34 PM, Alexander Pototskiy ***@***.***> wrote:﻿
You don't need to put libs from xcframework directly. Just add lua.xcframewtork into the project ( https://www.simpleswiftguide.com/how-to-add-xcframework-to-xcode-project/ ) and Xcode will find the appropriate lib automatically for the selected platform. But it's much more comfortable to use cocoapods to manage external dependencies like lua-iosx.

**Comment by apotocki** [comment]
You are welcome!
